language: python
sudo: required
dist: xenial

matrix:
  include:
    - python: 3.4
      env:
        - BUILD_DOCS=false
        - MAKE_TESTS=true
    - python: 3.5
      env:
        - BUILD_DOCS=false
        - MAKE_TESTS=true
    - python: 3.6
      env:
        - BUILD_DOCS=false
        - MAKE_TESTS=true
    - python: 3.7
      env:
        - BUILD_DOCS=true
        - MAKE_TESTS=true
    - python: 3.8
      env:
        - BUILD_DOCS=false
        - MAKE_TESTS=true

branches:
  only:
    - master
    - dev
    - /^fix-.*$/
    - /^feature-.*$/
    # Regex to build tagged commits with version numbers
    - /\d+\.\d+(\.\d+)?(\S*)?$/

before_install:
  # determine whether to skip build_docs or make_tests based on commit message
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ '[skip docs]' ]]; then export BUILD_DOCS=false; fi
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ '[skip tests]' ]]; then export MAKE_TESTS=false; fi

install:
  # -e is important for coverage report
  - pip install sphinx==1.6.7 # the theme not working with sphinx 1.7.0
  - pip install -e .[dev]
  # install win32tools
  - if [ "$MAKE_TESTS" == "true" ]; then
      bash ci/install-win32tools.sh;
      export PATH=${PATH}:${PWD}/win32tools/bin;
      sed -i "s/test_username/${HINET_USERNAME}/" tests/test_*.py;
      sed -i "s/test_password/${HINET_PASSWORD}/" tests/test_*.py;
    fi

script:
  - if [ "$MAKE_TESTS" == "true" ]; then make test coverage; fi

after_success:
  - if [ "$BUILD_DOCS" == "true" ]; then make doc; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: docs/_build/html
  on:
    branch: master
    python: '3.7'
    condition: '$BUILD_DOCS == "true"'
