name: hinetpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pip
  - setuptools>=77
  - setuptools_scm>=6.2
  # Runtime dependencies
  - certifi
  - packaging
  - requests
  - urllib3
  # Build dependencies
  - python-build
  # Test dependencies
  - pytest
  - pytest-cov
  # Code style dependencies
  - ruff
  # Documentation dependencies
  - myst-parser
  - sphinx
  - sphinx-intl
  - sphinx-rtd-theme
  # Static type check dependencies
  - mypy
  - types-requests
